services:
  - type: web
    name: backend
    runtime: node
    plan: free
    rootDir: back-end
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: CLOUDINARY_CLOUD_NAME
        value: ${CLOUDINARY_CLOUD_NAME}
      - key: CLOUDINARY_API_KEY
        value: ${CLOUDINARY_API_KEY}
      - key: CLOUDINARY_API_SECRET
        value: ${CLOUDINARY_API_SECRET}
      - key: CLOUDINARY_FOLDER
        value: ${CLOUDINARY_FOLDER}
