name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/4 * * * *"  # Every 4 minutes
  workflow_dispatch:       # Manual trigger option

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HEAD request to keep backend alive
        run: curl -I -s https://backend-3497.onrender.com/ping || echo "Ping failed"
